# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Label Stale

on:
    workflow_dispatch:
        inputs:
            dry-run:
                description: "Run in dry-run/debug-only mode."
                required: true
                type: boolean
                default: true
    schedule:
        - cron: "39 22 * * *"

jobs:
    stale:
        runs-on: ubuntu-latest
        permissions:
            issues: write
            pull-requests: write

        steps:
            - uses: actions/stale@v5
              env:
                  DEFAULT_DEBUG: false
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  stale-issue-message: "This issue has not had any activity for an extended period of time and is thus automatically being marked as stale.\n\n Author, you can help out by closing this issue if the problem no longer exists, or adding more information."
                  stale-pr-message: "This pull request has not had any activity for an extended period of time and is thus automatically being marked as stale.\n\n Assignee(s), you can help out by labeling this pull request as a work-in-progress if it is still being actively worked on, or closing it if not."
                  stale-issue-label: "stale"
                  stale-pr-label: "stale"
                  # Additional input options -------------------------------------------------------------------------
                  exempt-issue-labels: "awaiting-approval,work-in-progress"
                  exempt-pr-labels: "awaiting-approval,work-in-progress"
                  any-of-labels: "awaiting-feedback,awaiting-answers,info-needed"
                  close-issue-message: "This issue has been closed automatically because it needs more information and has not had recent activity."
                  close-pr-message: "This pull request has been closed automatically because it has not been labeled as a work-in-progress and has not had recent activity."
                  debug-only: ${{ inputs.dry-run || env.DEFAULT_DEBUG}}
                  days-before-stale: 30
